site_name: Amanda Jarvis - MDEF Docs
site_description: Master in Design for Emergent Futures
site_author: Amanda Jarvis
copyright: Copyleft 2022 "Amanda Jarvis" - GNU Free Documentation License
repo_name: 'agjarv/MDEF'
site_url: https://agjarv.github.io/MDEF/
repo_url: 'https://github.com/agjarv/MDEF'


theme:
  name: material

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: amber
      toggle: 
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: amber
      toggle: 
        icon: material/weather-night
        name: Switch to light mode
  font:
    text: Noto Sans
    code: Roboto Mono
  icon:
    logo: material/alpha-x-box-outline
    repo: material/gitlab
  favicon: images/alpha-x-box.png
  
  # Selected language English 
  language: en
  # Added navigation and search features
  features:
    # - announce.dismiss
    - content.code.annotate
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.indexes
    # - navigation.instant
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate

extra:
  social:
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/agjarv
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/agjarv/
    - icon: fontawesome/solid/paper-plane
      link: mailto:<agjarv@gmail.com>
    - icon: fontawesome/solid/globe
      link: https://couture.tech
    - icon: fontawesome/brands/github
      link: "https://github.com/agjarv/"

plugins:
  - search
  - git-revision-date-localized:
     enable_creation_date: true
     # enabled: !ENV [CI, false]

# navigation tree

nav:
  - Home: index.md
  - Reflections: 
    - reflections/index.md
    - Term 1: term01/term01.md
