site_name: Amanda Jarvis - MDEF Docs
site_description: Master in Design for Emergent Futures
site_author: Amanda Jarvis
copyright: Copyleft 2022 "Amanda Jarvis" - GNU Free Documentation License
repo_name: 'Page Source'
site_url: https://agjarv.github.io/MDEF/
repo_url: 'https://github.com/agjarv/MDEF'



theme:
  name: material

  palette:
    primary: black
    accent: amber
    
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle: material/weather-sunny
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle: material/weather-night
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    logo: material/alpha-x-box-outline
    repo: material/gitlab
  favicon: images/alpha-x-box.png
  
  features:
    - navigation.tabs


  extra:
  social:
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/agjarv
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/agjarv/
    - icon: fontawesome/solid/paper-plane
      link: mailto:<agjarv@gmail.com>
    - icon: fontawesome/solid/globe
      link: https://couture.tech
    - icon: fontawesome/brands/github
      link: "https://github.com/agjarv/"